version: '3'

services:
  elastic:
    image: elasticsearch:7.13.4
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true

  kibana:
    image: kibana:7.13.4
    ports:
      - 5601:5601  # web ui
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - elastic

  apm:
    image: elastic/apm-server:7.13.4
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elastic:9200"]
    depends_on:
      - elastic
      - kibana

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686  # web UI

  prometheus:
    image: ubuntu/prometheus
    ports:
      - 9090:9090  # web UI
    volumes:
      - ./confs/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  otel:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./confs/otel.yml:/etc/otel/config.yaml:ro
    ports:
      - 55680:55680  # legacy gRPC receiver
      - 4317:4317    # gRPC receiver
    depends_on:
      - apm
      - jaeger
