version: '3'

services:
  # Adapted from:
  #   https://www.elastic.co/guide/en/apm/get-started/current/quick-start-overview.html
  elastic:
    image: elasticsearch:7.13.4
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true

  # Adapted from:
  #   https://www.elastic.co/guide/en/apm/get-started/current/quick-start-overview.html
  kibana:
    image: kibana:7.13.4
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - elastic

  # Adapted from:
  #   https://www.elastic.co/guide/en/apm/get-started/current/quick-start-overview.html
  apm:
    image: elastic/apm-server:7.13.4
    ports:
      - 8200:8200
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elastic:9200"]
    depends_on:
      - elastic
      - kibana

  # Adapted from:
  #   https://www.jaegertracing.io/docs/1.24/getting-started/#all-in-one
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  # Adapted from:
  #   https://prometheus.io/docs/prometheus/latest/installation/#using-docker
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./confs/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # Adapted from:
  #   https://opentelemetry.io/docs/collector/getting-started/#docker
  #   https://github.com/open-telemetry/opentelemetry-collector/blob/main/examples/demo/docker-compose.yaml
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./confs/otel.yml:/etc/otel/config.yaml:ro
    ports:
      - 4317:4317  # gRPC
